services:
  db:
    image: postgres:16
    container_name: scm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: scm_db
      POSTGRES_USER: scm_user
      POSTGRES_PASSWORD: scm_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: scm_django_web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./secrets:/app/secrets
    depends_on:
      - db

volumes:
  postgres_data:
