services:
    db:
        image: postgres:16
        container_name: scm_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: scm_db
            POSTGRES_USER: scm_user
            POSTGRES_PASSWORD: scm_pass
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

    web:
        build: .
        container_name: scm_django_web
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./secrets:/app/secrets
            - ./certs:/app/certs
        depends_on:
            - db
        networks:
            - app_network

    registry:
        image: registry:2
        container_name: scm_registry
        volumes:
            - registry-data:/var/lib/registry
            - ./certs:/certs
            - ./registry-config.yml:/etc/docker/registry/config.yml:ro
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
            - app_network

    nginx:
        image: nginx:latest
        container_name: scm_nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
            - registry
        networks:
            - app_network

networks:
    app_network:

volumes:
    postgres_data:
    registry-data:
